allowBuilds:
  esbuild: true
  msw: true
  secp256k1: true
  sharp: true
  snyk: true
  unrs-resolver: true

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - dompurify@3.4.7
  - isomorphic-dompurify@3.15.0

trustPolicy: no-downgrade
