import { NextResponse, type NextRequest } from 'next/server';
import { Rola } from '@radixdlt/rola';
import { isValidChallenge } from '../challenge/route';
import { supabaseAdmin } from '@/lib/supabase';
import { RadixNetworkId, NETWORKS } from '@/features/wallet/constants/network';
import {
  createSessionJWT,
  verifySessionJWT,
  buildSessionCookieHeader,
  type NetworkSessionData,
  type SessionPayload,
} from '@/lib/auth/session';

// ─── Types ──────────────────────────────────────────────────────────────────────

interface VerifyRequestBody {
  challenge: string;
  proof: {
    publicKey: string;
    signature: string;
    curve: 'curve25519' | 'secp256k1';
  };
  identityAddress: string;
  networkId: number; // 1 = Mainnet, 2 = Stokenet
  accounts: { address: string; label: string; appearanceId: number }[];
  personaLabel?: string;
}

// ─── Helpers ────────────────────────────────────────────────────────────────────

/**
 * Build a ROLA verifier for the given network on-the-fly.
 * We do NOT use a singleton because the user can connect to either network.
 */
function createRolaForNetwork(networkId: RadixNetworkId) {
  const config = NETWORKS[networkId];
  return Rola({
    networkId: config.networkId,
    applicationName: 'Radix Community',
    dAppDefinitionAddress: config.dAppDefinitionAddress,
    expectedOrigin: process.env.NEXT_PUBLIC_APP_URL
      || (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'http://localhost:3000'),
  });
}

function networkLabel(id: number): 'mainnet' | 'stokenet' {
  return id === RadixNetworkId.Mainnet ? 'mainnet' : 'stokenet';
}

// ─── POST /api/auth/radix/verify ────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  try {
    const body: VerifyRequestBody = await req.json();
    const {
      challenge,
      proof,
      identityAddress,
      networkId,
      accounts = [],
      personaLabel,
    } = body;

    // 1. Validate required fields
    if (!challenge || !proof || !identityAddress || !networkId) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 },
      );
    }

    // 2. Verify challenge was generated by us and hasn't expired
    const challengeValid = await isValidChallenge(challenge);
    if (!challengeValid) {
      return NextResponse.json(
        { error: 'Invalid or expired challenge' },
        { status: 401 },
      );
    }

    // 3. Verify the ROLA proof against the correct network
    const rola = createRolaForNetwork(networkId as RadixNetworkId);
    const result = await rola.verifySignedChallenge({
      challenge,
      proof,
      address: identityAddress,
      type: 'persona',
    });

    if (result.isErr()) {
      return NextResponse.json(
        { error: 'Invalid signature' },
        { status: 401 },
      );
    }

    // 4. UPSERT wallet session in Supabase
    const net = networkLabel(networkId);
    const { error: upsertError } = await supabaseAdmin
      .from('wallet_sessions')
      .upsert(
        {
          identity_address: identityAddress,
          network: net,
          persona_label: personaLabel || null,
          accounts: JSON.stringify(accounts),
          updated_at: new Date().toISOString(),
          last_seen_at: new Date().toISOString(),
        },
        { onConflict: 'identity_address,network' },
      );

    if (upsertError) {
      return NextResponse.json(
        { error: 'Failed to save session' },
        { status: 500 },
      );
    }

    // 5. Build JWT payload — preserve existing session for the OTHER network
    const existingToken = req.cookies.get('radix-session')?.value;
    let existingSession: SessionPayload | null = null;
    if (existingToken) {
      existingSession = await verifySessionJWT(existingToken);
    }

    const newNetworkSession: NetworkSessionData = {
      identityAddress,
      personaLabel: personaLabel || '',
      accounts,
    };

    const jwtPayload: Pick<SessionPayload, 'mainnet' | 'stokenet'> = {
      mainnet: existingSession?.mainnet ?? null,
      stokenet: existingSession?.stokenet ?? null,
    };
    jwtPayload[net] = newNetworkSession;

    // 6. Sign JWT and set cookie
    const token = await createSessionJWT(jwtPayload);
    const response = NextResponse.json({
      success: true,
      identityAddress,
      network: net,
    });
    response.headers.set('Set-Cookie', buildSessionCookieHeader(token));

    return response;
  } catch {
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 },
    );
  }
}
