import { NextResponse } from 'next/server';
import { Rola } from '@radixdlt/rola';
import { isValidChallenge } from '../challenge/route';
import { supabase } from '@/lib/supabase';

import { RadixNetworkId } from '@/features/wallet/constants/network';

// Helper to get network ID based on env
const getNetworkId = () => {
    const network = process.env.NEXT_PUBLIC_RADIX_NETWORK;
    return network === 'mainnet' ? RadixNetworkId.Mainnet : RadixNetworkId.Stokenet;
};

// Helper to get DApp address
const getDAppAddress = () => {
    const network = process.env.NEXT_PUBLIC_RADIX_NETWORK;
    return network === 'mainnet' 
        ? process.env.NEXT_PUBLIC_RADIX_DAPP_ADDRESS_MAINNET 
        : process.env.NEXT_PUBLIC_RADIX_DAPP_ADDRESS_STOKENET;
};

const rola = Rola({
    networkId: getNetworkId(),
    applicationName: 'Radix Community',
    dAppDefinitionAddress: getDAppAddress() || 'account_tdx_2_129grv2vv4q3w7aqzzwesc5k0xp4lg5dj4p78q80ca79rj5rct8mujk',
    expectedOrigin: process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000',
});

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { challenge, proof, identityAddress } = body;

    if (!challenge || !proof || !identityAddress) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    // 1. Verify challenge was generated by us and hasn't expired
    if (!isValidChallenge(challenge)) {
        return NextResponse.json({ error: 'Invalid or expired challenge' }, { status: 401 });
    }

    // 2. Verify the ROLA proof
    const result = await rola.verifySignedChallenge({
        challenge,
        proof,
        address: identityAddress,
        type: 'persona'
    });

    if (result.isErr()) {
        console.error("ROLA Verification failed:", result.error);
        return NextResponse.json({ error: 'Invalid signature' }, { status: 401 });
    }

    // 3. Signature is valid! Find or create user in Supabase
    // Note: This requires a 'users' or 'profiles' table with 'radix_address' column.
    
    // We are just finding the user for now to demonstrate the flow.
    // Real implementation requires Custom Auth token generation using supabase admin.
    const { data: user, error: userError } = await supabase
        .from('profiles') // Assuming a profiles table exists
        .select('*')
        .eq('radix_address', identityAddress)
        .single();

    if (userError && userError.code !== 'PGRST116') {
        console.error("Supabase error:", userError);
        // We continue anyway just for the sake of the demo, in a real app you might fail here
    }

    // If user doesn't exist, we could insert them here.
    if (!user && userError?.code === 'PGRST116') {
         console.log("User not found, would create new profile for:", identityAddress);
         // await supabase.from('profiles').insert({ radix_address: identityAddress })
    }

    // Generate a secure session cookie here (JWT or NextAuth session)
    // For now, return success to the client
    return NextResponse.json({ 
        success: true, 
        message: 'Identity verified successfully',
        identityAddress
    });

  } catch (error) {
    console.error('ROLA Verify Error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
