/**
 * services/gateway/protocolVotes.ts
 *
 * The protocol-update signal a validator has actually cast, read from the
 * ledger.
 *
 * There is no field to read this from: `/state/validators/list` carries the
 * validator's whole substate (stake, fee, keys, registration) and nothing
 * about readiness, and the stream's event filter only understands Deposit and
 * Withdrawal. The signal exists solely as a
 * `ProtocolUpdateReadinessSignalEvent` in the receipt of the transaction that
 * cast it, so the only way to know is to look for that event.
 *
 * Scanning every validator that way is far too expensive, which is why the
 * repo used to ship a snapshot regenerated by hand (`scripts/update-protocol-
 * votes.ts`). That snapshot only ever held mainnet addresses, so on Stokenet a
 * vote could never be read back at all and the card kept offering to cast it
 * again. This reads the signal live instead, for the handful of validators the
 * connected wallet owns, which are the only ones whose badge is actionable.
 *
 * The scan runs forwards from the epoch the current update was announced in:
 * a vote is cast once and stays cast, so it sits near the start of that range
 * rather than near the ledger tip, where a busy validator buries it under
 * thousands of staking transactions.
 */

import { getGateway, withRetry, type Network } from './client';
import logger from '@/lib/logger';
import { getRedis } from '@/lib/redis';
import { protocolSignal } from '@/features/dashboard/staking/constants/protocolUpdate';

/**
 * Where the scan starts on each network. Mainnet begins at the epoch
 * Cuttlefish signalling opened, which is what makes a single page enough for
 * most validators; Stokenet is young enough that its whole history is cheap.
 */
const START_EPOCH: Record<Network, number> = {
    mainnet: 150_000,
    stokenet: 1,
};

/** Pages of transactions read per validator before giving up. */
const MAX_PAGES = 5;
const PAGE_SIZE = 100;

/** A cast vote never changes, so it is held far longer than a missing one. */
const TTL_VOTED_S = 24 * 60 * 60;
const TTL_NOT_VOTED_S = 2 * 60;

type StreamEvent = { name?: string; data?: { fields?: Array<{ field_name?: string; value?: string }> } };
type StreamItem = { receipt?: { events?: StreamEvent[] } };

const cacheKey = (network: Network, address: string) => `protocol_vote_${network}_${address}`;

/** The version name carried by a readiness event, if that is what this is. */
function readSignal(event: StreamEvent): string {
    if (!event?.name?.includes('ProtocolUpdateReadinessSignal')) return '';
    const field = event.data?.fields?.find((f) => f.field_name === 'protocol_version_name');
    return (field?.value ?? '').trim();
}

/**
 * The validator's most recent signal, or '' when it has not signalled inside
 * the scanned range. Stops early once the configured target is found: that is
 * the answer the badge is asking about, and nothing later can override it.
 */
async function scanForSignal(validatorAddress: string, network: Network): Promise<string> {
    const gateway = getGateway(network);
    const target = protocolSignal(network);
    let cursor: string | undefined;
    let latest = '';

    for (let page = 0; page < MAX_PAGES; page++) {
        const res = await withRetry(() =>
            gateway.stream.innerClient.streamTransactions({
                streamTransactionsRequest: {
                    affected_global_entities_filter: [validatorAddress],
                    from_ledger_state: { epoch: START_EPOCH[network] },
                    order: 'Asc',
                    limit_per_page: PAGE_SIZE,
                    ...(cursor ? { cursor } : {}),
                    opt_ins: { receipt_events: true } as Parameters<
                        typeof gateway.stream.innerClient.streamTransactions
                    >[0]['streamTransactionsRequest']['opt_ins'],
                },
            }),
        );

        for (const item of (res.items ?? []) as StreamItem[]) {
            for (const event of item.receipt?.events ?? []) {
                const signal = readSignal(event);
                if (!signal) continue;
                if (signal === target) return signal;
                latest = signal;
            }
        }

        cursor = res.next_cursor ?? undefined;
        if (!cursor) break;
    }

    return latest;
}

/**
 * The signal this validator has cast, cached so a reload does not re-scan.
 * Returns '' when it has not voted, and on failure, because "we could not
 * read it" must not be shown as a vote the validator never made.
 */
export async function fetchValidatorProtocolVote(
    validatorAddress: string,
    network: Network = 'mainnet',
): Promise<string> {
    const redis = getRedis();
    const key = cacheKey(network, validatorAddress);

    if (redis) {
        try {
            const cached = await redis.get<string>(key);
            if (typeof cached === 'string') return cached;
        } catch (err) {
            logger.error({ err, network, validatorAddress }, '[ProtocolVotes] Cache read failed');
        }
    }

    try {
        const signal = await scanForSignal(validatorAddress, network);
        if (redis) {
            redis
                .set(key, signal, { ex: signal ? TTL_VOTED_S : TTL_NOT_VOTED_S })
                .catch((err) => logger.error({ err, network }, '[ProtocolVotes] Cache write failed'));
        }
        return signal;
    } catch (err) {
        logger.error({ err, network, validatorAddress }, '[ProtocolVotes] Scan failed');
        return '';
    }
}

/** The same read for a small set of validators, one entry per address. */
export async function fetchProtocolVotes(
    validatorAddresses: string[],
    network: Network = 'mainnet',
): Promise<Record<string, string>> {
    const unique = Array.from(new Set(validatorAddresses)).filter(Boolean);
    const signals = await Promise.all(
        unique.map((address) => fetchValidatorProtocolVote(address, network)),
    );
    return Object.fromEntries(unique.map((address, i) => [address, signals[i]]));
}

/**
 * Drops the cached answer for a validator, so the badge can be re-read from
 * the ledger as soon as a vote has been signed rather than after the TTL.
 */
export async function forgetProtocolVote(
    validatorAddress: string,
    network: Network = 'mainnet',
): Promise<void> {
    const redis = getRedis();
    if (!redis) return;
    try {
        await redis.del(cacheKey(network, validatorAddress));
    } catch (err) {
        logger.error({ err, network, validatorAddress }, '[ProtocolVotes] Cache drop failed');
    }
}
