'use client';

import React, { createContext, use, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useStakingTransaction } from '../hooks/useStakingTransaction';
import {
    apiFetchProtocolVotes,
    apiForgetProtocolVote,
} from '@/features/dashboard/services/apiClient';
import {
    protocolSignal,
    protocolName,
    protocolTargetEnabled,
    hasVotedTarget,
    type VoteNetwork,
} from '../constants/protocolUpdate';

interface VoteTargetValidator {
    address: string;
    ownerBadge?: string;
}

interface ProtocolVoteContextValue {
    /** The ledger these validators and this vote belong to. */
    network: VoteNetwork;
    /** A valid 32-char target is configured for this network. */
    enabled: boolean;
    /** The exact protocol version name signalled on-ledger. */
    signal: string;
    /** Human-friendly label for the target. */
    name: string;
    /** Whether the connected wallet owns this validator (can sign the vote). */
    canVote: (validatorAddress: string) => boolean;
    /**
     * The signal this validator has cast: read back from the ledger, or the
     * one just signed. Empty when it has not voted.
     */
    votedSignal: (validatorAddress: string) => string;
    /** Optimistic flag: the vote tx for this validator was just accepted. */
    hasJustVoted: (validatorAddress: string) => boolean;
    /** Address of the validator whose vote is currently in flight, if any. */
    votingAddress: string | null;
    /** Send the signal_protocol_update_readiness transaction to the wallet. */
    vote: (validator: VoteTargetValidator) => Promise<void>;
    error: string | null;
}

const ProtocolVoteContext = createContext<ProtocolVoteContextValue | undefined>(undefined);

/**
 * Optional consumer. Returns `undefined` outside a provider, so presentational
 * badges (e.g. the explorer detail view) keep working in display-only mode.
 */
export const useProtocolVote = () => use(ProtocolVoteContext);

/**
 * How long a read-back signal is trusted before asking again. A cast vote does
 * not change, so this only governs how quickly a fresh one is noticed.
 */
const VOTES_STALE_MS = 60_000;

export const ProtocolVoteProvider = ({
    ownerValidatorMap,
    network = 'mainnet',
    children,
}: {
    /** validator address → connected account that owns it. */
    ownerValidatorMap: Record<string, string>;
    /** The ledger on screen; mainnet and Stokenet signal different names. */
    network?: VoteNetwork;
    children: React.ReactNode;
}) => {
    const { submitProtocolVote, isTransacting, error } = useStakingTransaction();
    const [votingAddress, setVotingAddress] = useState<string | null>(null);
    /** Keyed by network so a ledger switch cannot inherit the other's votes. */
    const [justVoted, setJustVoted] = useState<Record<string, string>>({});

    const signal = protocolSignal(network);
    const name = protocolName(network);
    const enabled = protocolTargetEnabled(network);

    /*
     * The validators this wallet owns are the only ones whose badge is a
     * button, so they are the only ones worth reading live. Sorted so the same
     * set of owners is the same query key however the map was built.
     */
    const ownedAddresses = Object.keys(ownerValidatorMap).sort();

    /*
     * The validator list carries a vote from a snapshot that is regenerated by
     * hand and only ever held mainnet addresses. Reading the owned validators
     * from the ledger is what lets a reload show the vote that was just cast
     * rather than offering to cast it again.
     */
    const { data: liveVotes } = useQuery({
        enabled: ownedAddresses.length > 0,
        queryKey: ['protocol-votes', network, ownedAddresses],
        queryFn: () => apiFetchProtocolVotes(ownedAddresses, network),
        staleTime: VOTES_STALE_MS,
        retry: 1,
    });

    const canVote = (addr: string) => !!ownerValidatorMap[addr];

    const votedSignal = (addr: string) =>
        justVoted[`${network}:${addr}`] || liveVotes?.votes?.[addr] || '';

    const vote = async (validator: VoteTargetValidator) => {
        if (!enabled || isTransacting) return;
        // Already signalled this target: the wallet must not be asked to sign
        // and pay for a transaction that would change nothing on the ledger.
        if (hasVotedTarget(votedSignal(validator.address), network)) return;

        const account = ownerValidatorMap[validator.address];
        if (!account || !validator.ownerBadge) return;

        setVotingAddress(validator.address);
        const hash = await submitProtocolVote(
            account,
            validator.address,
            validator.ownerBadge,
            signal,
        );
        if (hash) {
            setJustVoted(prev => ({ ...prev, [`${network}:${validator.address}`]: signal }));
            /*
             * The server's cached answer was read before this vote existed.
             * It is dropped rather than re-read here: the transaction may not
             * have committed yet, and caching "has not voted" a second time is
             * exactly what made the button come back after a reload.
             */
            void apiForgetProtocolVote(validator.address, network);
        }
        setVotingAddress(null);
    };

    const value: ProtocolVoteContextValue = {
        network,
        enabled,
        signal,
        name,
        canVote,
        votedSignal,
        hasJustVoted: (addr: string) => !!justVoted[`${network}:${addr}`],
        votingAddress,
        vote,
        error,
    };

    return <ProtocolVoteContext.Provider value={value}>{children}</ProtocolVoteContext.Provider>;
};
