/**
 * Regenerates `lib/generated/og-backdrop.ts`, the artwork behind every social
 * share card, from the console sidebar graphic itself.
 *
 * Run with `pnpm gen:og-backdrop` whenever `SidebarGraphic` changes.
 *
 * Why a build step and not a render at request time: the app router refuses to
 * import `react-dom/server`, and transcribing 690 lines of nodes, links and
 * glass panels by hand would have been a copy that went stale the first time
 * the original was touched. Generating from the real component keeps one source
 * of truth with an explicit regeneration step, exactly as `gen:seal-svg` does.
 *
 * Two things are resolved on the way out, because a card is rasterised with no
 * browser and no stylesheet:
 *
 *   theme tokens   the SVG paints with `var(--sidebar-*)`, which nothing would
 *                  resolve, so `radix-dark` values are substituted literally
 *   aspect         the graphic is drawn 1200x560 and a card is 1200x630, so it
 *                  is cropped rather than stretched
 *
 * Its own headline is left empty: the card lays type out in satori, which
 * wraps, clamps and has the fonts, none of which SVG text does.
 */
import { renderToStaticMarkup } from 'react-dom/server';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { SidebarGraphic } from '../components/ui/SidebarGraphic';
import { ThemeProvider } from '../context/ThemeContext';

const WIDTH = 1200;
const HEIGHT = 630;

/** `radix-dark` values of every token the graphic paints with. */
const DARK_TOKENS: Record<string, string> = {
  'sidebar-bg': '#040920',
  'sidebar-primary': '#3B9BFF',
  'sidebar-secondary': '#2BDFAA',
  'sidebar-text-main': '#ffffff',
  'sidebar-grad1': '#00E5A0',
  'sidebar-grad-mid': '#1B3FCC',
  'sidebar-grad2': '#d829aa',
  'sidebar-shadow': '#000105',
  'sidebar-shadow2': '#01020a',
  'sidebar-glow-op-1': '0.5',
  'sidebar-glow-op-2': '0.55',
  'sidebar-glow-op-3': '0.18',
  'sidebar-net-primary': '#3B9BFF',
  'sidebar-net-secondary': '#2BDFAA',
  'sidebar-net-thick': '#ffffff',
  'sidebar-node-fill': '#ffffff',
  'sidebar-net-opacity': '0.85',
  'sidebar-layer-shadow': '#020518',
  'sidebar-comm-lines': 'rgba(255,255,255,0.12)',
  'sidebar-card-base': '#000105',
  'sidebar-card-stroke': '#000000',
  'sidebar-card-mid-stroke': 'rgba(0,0,0,0.6)',
  // Neither of these is declared in any theme, so on the site itself they
  // resolve to nothing. Given a value here rather than left broken; drop them
  // if the sidebar ever declares its own.
  'sidebar-atom-rings': '#3B9BFF',
  'sidebar-check-glow': '#2BDFAA',
};

const markup = renderToStaticMarkup(
  <ThemeProvider initialTheme="radix-dark">
    <SidebarGraphic appName="" title="" subtitle="" variant="default" />
  </ThemeProvider>,
);

const unresolved = new Set<string>();
const svg = markup
  .replace(/var\(--([a-z0-9-]+)\)/g, (whole, token: string) => {
    if (DARK_TOKENS[token]) return DARK_TOKENS[token];
    unresolved.add(token);
    return whole;
  })
  // `slice` crops the 560-tall drawing to the card instead of squashing it.
  .replace(/<svg /, `<svg width="${WIDTH}" height="${HEIGHT}" preserveAspectRatio="xMidYMid slice" `);

if (unresolved.size > 0) {
  console.error(`Unresolved theme tokens: ${[...unresolved].join(', ')}`);
  process.exit(1);
}

const target = resolve(process.cwd(), 'lib/generated/og-backdrop.ts');
writeFileSync(
  target,
  `// GENERATED by \`pnpm gen:og-backdrop\` from components/ui/SidebarGraphic.
// Do not edit: change the component and regenerate.
export const OG_BACKDROP_BASE = '${DARK_TOKENS['sidebar-bg']}';
export const OG_BACKDROP_DATA_URI =
  'data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}';
`,
);
console.log(`Wrote ${target} (${(svg.length / 1024).toFixed(1)} KB of SVG)`);
